### ISSUE TITLE
[FR] Ability to set metadata on GGUF files

### ISSUE THREAD

**Issue by nyxkrage** [PygmalionAI/quantizers#1]
This would be useful to override certain settings for the quantized models, such as the context size for mistral 0.1 models, where llamacpp doesn't support SWA for the full 32k context or for llama3 models where llamcpp incorrectly detects the pretokenizer as smaug-bpe instead of llama-bpe

See [gguf-py:gguf-set-metadata.py](https://github.com/ggerganov/llama.cpp/blob/master/gguf-py/scripts/gguf-set-metadata.py) for upstream implementation of this

I imagine it would look like an option in the yaml like so
```yaml
gguf:
  enabled: true
  # ...
  metadata:
    tokenizer.ggml.pre: llama-bpe
    # ...
```
